import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#b6d6c9",
        "on-primary-fixed": "#00201a",
        "inverse-surface": "#21342e",
        "primary-fixed": "#c8eadf",
        "surface-dim": "#c9dfd6",
        "tertiary-container": "#2f1500",
        "secondary-fixed-dim": "#a0d1bc",
        "on-error": "#ffffff",
        "on-surface-variant": "#414846",
        "on-secondary-fixed-variant": "#204f3f",
        "primary": "#072821",
        "surface-container": "#ddf3ea",
        "primary-container": "#072821",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-variant": "#d2e7df",
        "error-container": "#ffdad6",
        "secondary-container": "#b6e8d2",
        "surface-tint": "#45645c",
        "secondary": "#396756",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#bbedd7",
        "on-secondary-container": "#204f3f",
        "on-secondary-fixed": "#002117",
        "on-background": "#0c1f1a",
        "surface-container-highest": "#d2e7df",
        "tertiary": "#000000",
        "surface-bright": "#e8fef5",
        "surface-container-high": "#d7ede4",
        "on-tertiary-container": "#8a4900",
        "primary-fixed-dim": "#accec3",
        "inverse-on-surface": "#e0f6ed",
        "outline-variant": "#c1c8c4",
        "on-primary-fixed-variant": "#2e4c44",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "inverse-primary": "#accec3",
        "on-surface": "#0c1f1a",
        "surface-container-low": "#e3f9f0",
        "on-tertiary-fixed-variant": "#6e3900",
        "background": "#e8efe9",
        "on-tertiary-fixed": "#2f1500",
        "surface": "#e8fef5",
        "error": "#ba1a1a",
        "outline": "#717975",
        "tertiary-fixed": "#ffdcc3",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.25rem",
        xl: "1.75rem",
        "2xl": "2rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.875rem",
        "space-lg": "1.25rem",
        "space-xl": "1.75rem",
        margin: "1.25rem",
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "body-sm": ["Manrope", "system-ui", "sans-serif"],
        "body-md": ["Manrope", "system-ui", "sans-serif"],
        "body-lg": ["Manrope", "system-ui", "sans-serif"],
        "label-sm": ["Manrope", "system-ui", "sans-serif"],
        "label-md": ["Manrope", "system-ui", "sans-serif"],
        "headline-sm": ["Manrope", "system-ui", "sans-serif"],
        "headline-md": ["Manrope", "system-ui", "sans-serif"],
        "headline-lg": ["Manrope", "system-ui", "sans-serif"],
        "currency-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "currency-md": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "currency-lg": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "currency-display": ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "currency-display": ["34px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "currency-sm": ["13px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "currency-lg": ["20px", { lineHeight: "26px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "currency-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
